[workspace]
resolver = "3"
members = [
    "hello_rust",
    "guessing_game",
    "dice_roller_histo",
    "lsystem_plant_gen",
    "bevy_testing"
]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3